services:
    m3u-editor:
        # build:
        #     dockerfile: Dockerfile
        # image: "sail-8.4/app"
        image: sparkison/m3u-editor:dev
        ports:
            # - '${VITE_PORT:-5173}:${VITE_PORT:-5173}' # Vite (development)
            - "${REVERB_PORT:-36800}:${REVERB_PORT:-36800}" # Reverb
            - "${APP_PORT:-36400}:${APP_PORT:-36400}" # Laravel
            # - 36790:36790 # Redis
        environment:
            WWWUSER: "${WWWUSER}"
            LARAVEL_SAIL: 1
            XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
            XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
            IGNITION_LOCAL_SITES_PATH: "${PWD}"
        volumes:
            - "./docker-config:/var/www/config"
        networks:
            - sail
        # depends_on:
        #     - mariadb

    # mariadb:
    #     image: yobasystems/alpine-mariadb:10
    #     ports:
    #         - "${FORWARD_DB_PORT:-3309}:3306"
    #     environment:
    #         MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    #         MYSQL_ROOT_HOST: "%"
    #         MYSQL_DATABASE: "${DB_DATABASE}"
    #         MYSQL_USER: "${DB_USERNAME}"
    #         MYSQL_PASSWORD: "${DB_PASSWORD}"
    #         MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    #     volumes:
    #         - "./storage/mariadb/database:/var/lib/mysql"
    #         - "./docker/mariadb/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh"
    #     networks:
    #         - sail
    #     healthcheck:
    #         test:
    #             - CMD
    #             - mysqladmin
    #             - ping
    #             - "-p${DB_PASSWORD}"
    #         retries: 3
    #         timeout: 5s

networks:
    sail:
        driver: bridge
